[Open in Colab](https://colab.research.google.com/github/WoolierBrooks/DementiaDetect-Speech/blob/main/scripts/adress_2020/00_Complete_nb.ipynb)

Importar bibliotecas

In [1]:
import pandas as pd
import numpy as np

Importar o dataset de treino

In [2]:
dataset = pd.read_csv("adress_20_db_egemaps_train.csv")
X_train = dataset.iloc[:, :-1].values
y_train = dataset.iloc[:, -1].values
print(X_train, X_train.shape)
print(y_train, y_train.shape)

[[ 26.2     0.256  23.5   ...   0.251   0.467 -29.5  ]
 [ 35.      0.222  32.1   ...   1.41    1.8   -43.9  ]
 [ 33.4     0.168  30.8   ...   0.291   0.738 -25.3  ]
 ...
 [ 32.      0.249  28.6   ...   0.236   0.464 -24.   ]
 [ 25.5     0.37   14.4   ...   0.109   0.118 -25.9  ]
 [ 29.7     0.318  19.9   ...   0.177   0.27  -22.   ]] (108, 88)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (108,)


Importando o dataset de teste

In [3]:
dataset = pd.read_csv("adress_20_db_egemaps_test.csv")
X_test = dataset.iloc[:, :-1].values
y_test = dataset.iloc[:, -1].values
print(X_test, X_test.shape)
print(y_test, y_test.shape)

[[ 3.14e+01  1.54e-01  3.02e+01 ...  3.02e-01  5.47e-01 -2.30e+01]
 [ 3.00e+01  1.18e-01  2.85e+01 ...  7.25e-01  1.36e+00 -5.75e+01]
 [ 1.96e+01  4.03e-01  1.38e+01 ...  5.59e-02  4.70e-02 -2.53e+01]
 ...
 [ 2.74e+01  3.42e-01  1.99e+01 ...  3.98e-01  7.33e-01 -2.94e+01]
 [ 2.82e+01  2.16e-01  2.51e+01 ...  3.76e-01  6.97e-01 -2.52e+01]
 [ 3.63e+01  2.00e-01  3.23e+01 ...  2.78e-01  4.74e-01 -4.00e+01]] (48, 88)
[0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0.
 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0.] (48,)


Completando dados faltantes

In [4]:
from sklearn.impute import SimpleImputer

# Conjunto de treino
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X_train)
X_train = imputer.transform(X_train)
print(X_train, X_train.shape)

[[ 26.2     0.256  23.5   ...   0.251   0.467 -29.5  ]
 [ 35.      0.222  32.1   ...   1.41    1.8   -43.9  ]
 [ 33.4     0.168  30.8   ...   0.291   0.738 -25.3  ]
 ...
 [ 32.      0.249  28.6   ...   0.236   0.464 -24.   ]
 [ 25.5     0.37   14.4   ...   0.109   0.118 -25.9  ]
 [ 29.7     0.318  19.9   ...   0.177   0.27  -22.   ]] (108, 88)


In [5]:
# Conjunto de teste
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X_test)
X_test = imputer.transform(X_test)
print(X_test, X_test.shape)

[[ 3.14e+01  1.54e-01  3.02e+01 ...  3.02e-01  5.47e-01 -2.30e+01]
 [ 3.00e+01  1.18e-01  2.85e+01 ...  7.25e-01  1.36e+00 -5.75e+01]
 [ 1.96e+01  4.03e-01  1.38e+01 ...  5.59e-02  4.70e-02 -2.53e+01]
 ...
 [ 2.74e+01  3.42e-01  1.99e+01 ...  3.98e-01  7.33e-01 -2.94e+01]
 [ 2.82e+01  2.16e-01  2.51e+01 ...  3.76e-01  6.97e-01 -2.52e+01]
 [ 3.63e+01  2.00e-01  3.23e+01 ...  2.78e-01  4.74e-01 -4.00e+01]] (48, 88)


Escalonamento de características

In [6]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train, X_train.shape)
print(X_test, X_test.shape)

[[-0.96499933  0.01608995 -0.25713585 ... -0.3075857  -0.42889569
   0.35704303]
 [ 1.31133564 -0.46621446  1.49380095 ...  0.79774868  0.75653521
  -0.98484514]
 [ 0.89745656 -1.23222735  1.22912445 ... -0.26943784 -0.18789661
   0.74842709]
 ...
 [ 0.53531236 -0.08320802  0.78121039 ... -0.32189115 -0.43156358
   0.86956977]
 [-1.14607143  1.63322826 -2.1098713  ... -0.44301062 -0.73925982
   0.69251508]
 [-0.05963883  0.89558623 -0.99008614 ... -0.37815925 -0.6040869
   1.05594313]] (108, 88)
[[ 0.3801077  -1.43082328  1.10696607 ... -0.25894718 -0.35775205
   0.96275645]
 [ 0.0179635  -1.94149854  0.76085066 ...  0.14446649  0.36524519
  -2.25218398]
 [-2.67225055  2.10134725 -2.23202968 ... -0.49365191 -0.8023998
   0.74842709]
 ...
 [-0.65459001  1.2360364  -0.99008614 ... -0.1673923  -0.19234309
   0.3663617 ]
 [-0.44765047 -0.551327    0.06861983 ... -0.18837363 -0.22435773
   0.75774575]
 [ 1.6476124  -0.77829379  1.53452041 ... -0.28183589 -0.42267062
  -0.62141709]] (48, 88)

Seleção univariada de características

In [134]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

print(X_train.shape)
print(X_test.shape)

# Inicializando e ajustando o seletor de características no conjunto de treino
selector = SelectKBest(f_classif, k=26)
X_train_new = selector.fit_transform(X_train, y_train)

# Aplicando as mesmas características selecionadas para o conjunto de teste
X_test_new = selector.transform(X_test)

print(X_train_new.shape)
print(X_test_new.shape)

(108, 88)
(48, 88)
(108, 26)
(48, 26)


Eliminação de características recursivas

In [145]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVC

print(X_train.shape)
print(X_test.shape)

# Inicializar o estimador do modelo
estimator = SVC(kernel="linear")

# Inicialize o RFE com o estimador e o número desejado de características a serem mantidas
rfe = RFE(estimator, n_features_to_select=26, step=1)
rfe.fit(X_train, y_train)

# Transforme os conjuntos de treino e teste de acordo com as características selecionadas
X_train_new = rfe.transform(X_train)
X_test_new = rfe.transform(X_test)

print(X_train_new.shape)
print(X_test_new.shape)

(108, 88)
(48, 88)
(108, 26)
(48, 26)


Seleção de características usando SelectFromModel

In [156]:
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import SVC

print(X_train.shape)
print(X_test.shape)

# Definindo o modelo que será usado para selecionar características
model = SVC(kernel="linear")

# Inicializando o seletor e ajustando ao conjunto de treino
selector = SelectFromModel(estimator=model, max_features=26)  # Selecionando 99 características
selector.fit(X_train, y_train)

# Aplicando a seleção de características aos conjuntos de treino e teste
X_train_new = selector.transform(X_train)
X_test_new = selector.transform(X_test)

print(X_train_new.shape)
print(X_test_new.shape)

(108, 88)
(48, 88)
(108, 26)
(48, 26)


Seleção sequencial de características

In [167]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.svm import SVC

print(X_train.shape)
print(X_test.shape)

# Inicializando o classificador
model = SVC(kernel="linear")

# Inicializando o Sequential Feature Selector
# Defina o número desejado de características e a direção (forward ou backward)
sfs = SequentialFeatureSelector(model, n_features_to_select=26, direction='forward')

# Ajustando o Sequential Feature Selector ao conjunto de treino
sfs.fit(X_train, y_train)

# Obtendo o novo conjunto de características para treino e teste
X_train_new = sfs.transform(X_train)
X_test_new = sfs.transform(X_test)

print(X_train_new.shape)
print(X_test_new.shape)                                                                                  

(108, 88)
(48, 88)
(108, 26)
(48, 26)


Testando Linear Discriminant Analysis (LDA)

In [168]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score

# Instanciando o classificador LDA
lda = LinearDiscriminantAnalysis()

# Treinando o modelo LDA com os dados de treinamento
lda.fit(X_train_new, y_train)

# Realizando previsões nos dados de teste
y_pred = lda.predict(X_test_new)

# Calculando a precisão da classificação
accuracy = accuracy_score(y_test, y_pred)
print(f"Acurácia do modelo: {accuracy * 100:.2f}%")

Acurácia do modelo: 58.33%


In [169]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import cross_val_score

# Instanciando o classificador LDA
lda = LinearDiscriminantAnalysis()

# Realizando cross-validation no conjunto de treino
scores = cross_val_score(lda, X_train_new, y_train, cv=2)

# Calculando a média das pontuações de validação cruzada
mean_accuracy = scores.mean()

print(f"Acurácia média do modelo: {mean_accuracy * 100:.2f}%")

Acurácia média do modelo: 58.33%


Testando Decision Tree (DT)

In [170]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Inicializa o classificador de árvore de decisão
clf = DecisionTreeClassifier(random_state=42)

# Treina o classificador com o conjunto de treino
clf.fit(X_train_new, y_train)

# Realiza a previsão com o conjunto de teste
y_pred = clf.predict(X_test_new)

# Calcula a acurácia do modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Acurácia do modelo: {accuracy * 100:.2f}%')

Acurácia do modelo: 62.50%


In [171]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

# Inicializa o classificador de árvore de decisão
clf = DecisionTreeClassifier(random_state=42)

# Realiza validação cruzada no conjunto de treinamento
scores = cross_val_score(clf, X_train_new, y_train, cv=2)

# Calcula a média das pontuações
mean_accuracy = scores.mean()

print(f'Acurácia média do modelo: {mean_accuracy * 100:.2f}%')

Acurácia média do modelo: 52.78%


Testando Rede Neural Simples (NN)

In [172]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Criando o classificador da rede neural
classifier = MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000, random_state=42)

# Treinando o classificador
classifier.fit(X_train_new, y_train)

# Realizando previsões no conjunto de teste
predictions = classifier.predict(X_test_new)

# Calculando a acurácia do modelo
accuracy = accuracy_score(y_test, predictions)
print(f'Acurácia do modelo: {accuracy * 100:.2f}%')

Acurácia do modelo: 60.42%


C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [173]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

# Criando o classificador da rede neural
classifier = MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000, random_state=42)

# Calculando as pontuações de validação cruzada
cv_scores = cross_val_score(classifier, X_train_new, y_train, cv=2)

# Calculando a média das pontuações de validação cruzada
mean_accuracy = cv_scores.mean()
print(f'Acurácia média do modelo: {mean_accuracy * 100:.2f}%')

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Acurácia média do modelo: 58.33%


C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testando Support Vector Machine (SVM)

In [174]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Criar um classificador SVM
classificador_svm = SVC(kernel='linear')  # Você pode escolher o tipo de kernel desejado

# Treinar o classificador SVM
classificador_svm.fit(X_train_new, y_train)

# Fazer previsões usando o conjunto de teste
predictions = classificador_svm.predict(X_test_new)

# Calculando a acurácia do modelo
accuracy = accuracy_score(y_test, predictions)
print(f'Acurácia do modelo: {accuracy * 100:.2f}%')

Acurácia do modelo: 56.25%


In [175]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

# Criar um classificador SVM
classificador_svm = SVC(kernel='linear')  # Você pode escolher o tipo de kernel desejado

# Treinar o classificador SVM com validação cruzada no conjunto de treino
scores = cross_val_score(classificador_svm, X_train_new, y_train, cv=2) 

# Calculando a acurácia média do modelo
mean_accuracy = scores.mean()
print(f'Acurácia média do modelo com validação cruzada: {mean_accuracy * 100:.2f}%')

Acurácia média do modelo com validação cruzada: 56.48%


Testando Random Forest (RF)

In [176]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Criando o classificador Random Forest
classificador_rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Treinando o classificador com os dados de treinamento
classificador_rf.fit(X_train_new, y_train)

# Fazendo previsões com o conjunto de teste
predictions = classificador_rf.predict(X_test_new)

# Calculando a acurácia do modelo
accuracy = accuracy_score(y_test, predictions)
print(f'Acurácia do modelo: {accuracy * 100:.2f}%')

Acurácia do modelo: 68.75%


In [177]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Criando o classificador Random Forest
classificador_rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Realizando a validação cruzada apenas no conjunto de treino
scores = cross_val_score(classificador_rf, X_train_new, y_train, cv=2)

# Exibindo a acurácia média da validação cruzada
print(f'Acurácia média da validação cruzada: {scores.mean() * 100:.2f}%')

Acurácia média da validação cruzada: 59.26%


Boxplot só para avaliar a dispersão  
Tecnicas de processamento de texto
